### ISSUE TITLE
If more than one song from the same album script crashs.

### ISSUE THREAD

**Issue by BoBeR182** [Laharah/redlist#1]
When adding a spotify playlist with several songs from the same album Redlist tries to download the same torrent twice, causing an error and crashing the script.

I would expect it to remove duplicate RED torrents, from the queue, or continue disregarding the error.

```
Deluge: Connected to localhost:58846
ERROR:redlist.__main__:Error Processing https://open.spotify.com/playlist/XXXXXXXXXXXXXXX.
Traceback (most recent call last):
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 220, in entry_point
    results.append(loop.run_until_complete(main(splist, options.yes)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 135, in main
    await asyncio.gather(*dls)
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 129, in add_torrent
    client.add_torrent_file(filename, data, paused)
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/deluge.py", line 40, in add_torrent_file
    res = self._client.call('core.add_torrent_file', filename, data, options)
  File "/home/bober/redlist/lib/python3.8/site-packages/deluge_client/client.py", line 247, in call
    return self._receive_response(self.deluge_version, self.deluge_protocol_version)
  File "/home/bober/redlist/lib/python3.8/site-packages/deluge_client/client.py", line 226, in _receive_response
    raise exception(exception_msg)
deluge_client.client.AddTorrentError: Torrent already in session (XXXXXXXXXXXXXXXXXXXXXXXXXXXX).
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/deluge/core/core.py", line 482, in add_torrent_file
    return self.torrentmanager.add(
  File "/usr/lib/python3.8/site-packages/deluge/core/torrentmanager.py", line 536, in add
    __, add_torrent_params = self._build_torrent_params(
  File "/usr/lib/python3.8/site-packages/deluge/core/torrentmanager.py", line 446, in _build_torrent_params
    raise AddTorrentError('Torrent already in session (%s).' % torrent_id)
deluge.error.AddTorrentError: Torrent already in session (XXXXXXXXXXXXXXXXXXXXXXXXXXXXX).

```

**Comment by Laharah** [comment]
Looks like deluge 3 raises an actual exception on duplicate torrents being added. I've stopped duplicate torrents being downloaded and added some error handling for pre-exsisting torrents.

Give the new version a try and let me know if it solves the issue.

**Comment by BoBeR182** [comment]
```
Traceback (most recent call last):
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 220, in entry_point
    results.append(loop.run_until_complete(main(splist, options.yes)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 133, in main
    for torrent in set(downloads.values())
TypeError: unhashable type: 'dict'

```

**Comment by Laharah** [comment]
Sorry, can't really test on my phone, give that a try.

**Comment by BoBeR182** [comment]
Looks patched, is it possible to not have it try the duplicates, by removing them before the REDAPI calls are made https://github.com/Laharah/redlist/blob/master/redlist/__main__.py#L59 here?
I don't know enough python to attempt this on my own.
```
matched = list(set(matched)) #maybe?
```

**Comment by Laharah** [comment]
I incorporated your suggestion. I couldn't prune the duplicates that early, it had to be after the tracks were matched to torrents on redacted. You can see the actual change here: 135fe84

I was able to get to a laptop and test properly, so version 0.2.4 should work as intended. Give it a shot, and if you run into any more issues let me know. I'm gonna mark this as closed for now, but feel free to re-open if you run into the same problem again.

Thanks for your help improving the tool!
