### ISSUE TITLE
ERROR:redlist:program pinentry could not be found in path

### ISSUE THREAD

**Issue by Zappy-01** [Laharah/redlist#10]
Whenever i run the command 'redlist', my cmd displays the error: 'ERROR:redlist:program pinentry could not be found in path.', followed by: 

> Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\Scripts\redlist.exe\__main__.py", line 4, in <module>
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\redlist\__main__.py", line 17, in <module>
    from . import redapi
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\redlist\redapi.py", line 3, in <module>
    import aiohttp
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\aiohttp\client.py", line 36, in <module>
    from . import hdrs, http, payload
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\aiohttp\http_parser.py", line 43, in <module>
    from .streams import EMPTY_PAYLOAD, StreamReader
  File "c:\users\hp\appdata\local\programs\python\python36-32\lib\site-packages\aiohttp\streams.py", line 4, in <module>
    from typing import Awaitable, Callable, Deque, Generic, List, Optional, Tuple, TypeVar
ImportError: cannot import name 'Deque'

I tried creating a new config file with the line "pinentry: no", but I'm not sure if I put it in the right directory or if that would even solve my issue.

Please help.

**Comment by Laharah** [comment]
I can help you with that. Looks like you're on windows. 

You can create a file with `pinentry: no` in it and then use the `--config <FILENAME>` option to use it.

If you want it to be more permanent, you can put the file in the `%APPDATA%\redlist` folder. You get to the appdata folder by going to `start -> run` then put in `%APPDATA%`. If the `redlist` folder isn't there, just make it and put your file in it. 

To avoid all this I recommend that you get an API key from [REDACTED]: `settings -> Access Settings -> API key`. You can put that in your config file like this:

```yaml
redacted:
    api_key: <KEY>
```
Once it's in there you won't have to put in a password again.

---

Weirdly that doesn't seem like the issue from the error code. The error says that it failed to import the aiohttp library. From what I can tell, the [aiohttp library](https://pypi.org/project/aiohttp/) requires python 3.8 or higher. You can download the newest version from https://www.python.org/

You'll also wanna try re-installing the plugin with `pip install git+https://github.com/Laharah/redlist.git --force-reinstall`.

LMK how you fair. And if you start getting a new error you can't sort, out feel free to post it here.

**Comment by Zappy-01** [comment]
Thankyou so much for replying even though I already found a solution to my problem. 

Yes, updating my python actually fixed my problem.
