### ISSUE TITLE
Escape slashes in playlistnames

### ISSUE THREAD

**Issue by BoBeR182** [Laharah/redlist#4]
```
Matching track list to beets library...
Finished. There are 205 tracks that could not be matched.
Writing m3u file to /home/bober/redlist/Glitch Hop/Chiptune/Electro Swing clusterfuck.m3u.
ERROR:redlist.__main__:Error Processing https://open.spotify.com/playlist/2b7k0QgxwU7p30TJhgstLM.
Traceback (most recent call last):
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 241, in entry_point
    results.append(loop.run_until_complete(main(splist, options.yes)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 57, in main
    playlist.create_m3u_from_info(matched, save_path)
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/playlist.py", line 46, in create_m3u_from_info
    with open(output, 'wb') as fout:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bober/redlist/Glitch Hop/Chiptune/Electro Swing clusterfuck.m3u'
```

**Comment by Laharah** [comment]
good catch, patched.
